@startuml

title __MCR_LABO1C's Class Diagram__\n

  package  {
    interface Bouncer.Bouncable {
    }
  }
  

  package  {
    class Bouncer.BounceApp {
    }
  }
  

  package  {
    abstract class Bouncer.Bouncer {
    }
  }
  

  package  {
    class Displayer.BouncerDisplayer {
    }
  }
  

  package  {
    abstract class Bouncer.Circle {
    }
  }
  

  package  {
    interface Displayer.Displayer {
    }
  }
  

  package  {
    class Factory.EmptyShapeFactory {
    }
  }
  

  package  {
    class Renderer.EmptyShapeRenderer {
    }
  }
  

  package  {
    class Factory.FilledShapeFactory {
    }
  }
  

  package  {
    class Renderer.FilledShapeRenderer {
    }
  }
  

  package  {
    class MotionVector {
    }
  }
  

  package  {
    interface Renderer.Renderable {
    }
  }
  

  package  {
    abstract class Factory.ShapeFactory {
    }
  }
  

  package  {
    abstract class Renderer.BouncerRenderer {
    }
  }
  

  package  {
    abstract class Bouncer.Square {
    }
  }
  

  Bouncer.BounceApp o-- Displayer.Displayer : displayer
  Bouncer.Bouncer -up-|> Bouncer.Bouncable
  Bouncer.Bouncer o-- MotionVector : mVector
  Displayer.BouncerDisplayer -up-|> Displayer.Displayer
  Bouncer.Circle -up-|> Bouncer.Bouncer
  Factory.EmptyShapeFactory -up-|> Factory.ShapeFactory
  Renderer.EmptyShapeRenderer -up-|> Renderer.Renderable
  Factory.FilledShapeFactory -up-|> Factory.ShapeFactory
  Renderer.FilledShapeRenderer -up-|> Renderer.Renderable
  Renderer.BouncerRenderer -up-|> Renderer.Renderable
  Bouncer.Square -up-|> Bouncer.Bouncer


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
